openapi: 3.0.3
info:
  title: Lynx Scanner
  description: Lynx Scanner API
  version: 1.0.0
servers:
  - url: 'http://localhost:{port}'
    description: Local server
    variables:
      port:
        default: '8080'
  - url: 'https://{stage}.lynx.ssegning.com'
    description: Production server
    variables:
      stage:
        default: 'dev'
        enum:
          - dev
          - api

tags:
  - name: file

paths:
  '/files/upload':
    post:
      summary: Upload a file
      tags: [ file ]
      operationId: uploadFile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileUploadResponse'
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FileUpload'
  '/files/download/{file_id}':
    get:
      summary: Get a file
      tags: [ file ]
      operationId: getFile
      parameters:
        - name: file_id
          in: path
          required: true
          description: File ID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: 'File not found'
        '500':
          description: 'Internal server error'

components:
  schemas:
    FileUpload:
      type: object
      properties:
        file:
          type: string
          format: binary
    FileUploadResponse:
      type: object
      properties:
        file_id:
          type: string