name: Generate Documentation for the frontend

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    generate-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Clone project
              uses: actions/checkout@v3

            - name: Generate docs in markdown
              run: yarn typedoc

            - name: Convert md to pdf files
              run: yarn convert-md-to-pdf

            - name: Upload PDF artifact
              uses: actions/upload-artifact@v3
              with:
                  name: documentations
                  path: ./docs/**/*.pdf